# Generated by Django 4.2.6 on 2023-12-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_model_author'),
        ('author', '0002_alter_author_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
