# Generated by Django 4.2.6 on 2024-01-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSite', '0011_borrowhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowhistory',
            name='borrowed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
