# Generated by Django 4.2.6 on 2024-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabletime',
            options={'verbose_name_plural': 'AvailableTime'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name_plural': 'Designation'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name_plural': 'Doctor'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name_plural': 'Specialization'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='availableTime',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availableTime',
            field=models.ManyToManyField(to='doctor.availabletime'),
        ),
    ]
