# Generated by Django 4.2.6 on 2024-01-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Review'},
        ),
    ]
