# Generated by Django 4.2.6 on 2024-01-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contract Us'},
        ),
    ]
