# Generated by Django 4.2.6 on 2023-12-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_model', '0001_initial'),
        ('task_catagory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagorymadel',
            name='TaskTitle',
        ),
        migrations.AddField(
            model_name='catagorymadel',
            name='TaskTitle',
            field=models.ManyToManyField(to='task_model.modeltask'),
        ),
    ]
