# Generated by Django 4.2.6 on 2023-12-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_catagory', '0002_remove_catagorymadel_tasktitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagorymadel',
            old_name='TaskTitle',
            new_name='AllTitle',
        ),
    ]
