# Generated by Django 4.2.6 on 2023-12-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_catagory', '0003_rename_tasktitle_catagorymadel_alltitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagorymadel',
            name='AllTitle',
        ),
    ]
