# Generated by Django 4.2.6 on 2023-12-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskTitle', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Assign_date', models.DateField()),
                ('Complited', models.BooleanField(default=False)),
            ],
        ),
    ]
