# Generated by Django 4.2.6 on 2024-01-13 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0002_rename_balance_after_transactions_transaction_balance_after_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money_transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userbankaccount')),
            ],
        ),
    ]
