# Generated by Django 4.2.6 on 2024-01-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_money_transfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Money_transfer',
        ),
    ]
