# Generated by Django 4.2.6 on 2024-01-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_delete_money_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='withdraw_approve',
            field=models.BooleanField(default=False),
        ),
    ]
