# Generated by Django 4.2.6 on 2024-01-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_withdraw_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='withdraw_approve',
        ),
    ]
