# Generated by Django 4.2.6 on 2023-12-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='school_name',
            field=models.TextField(default='Nabinagar'),
        ),
    ]
